# tomcat port
server:
  port: 9001

# jsp (파일경로)
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
      static-path-pattern: /resources/**
  devtools:
    livereload:
      enabled: true
  # 파일 업로드 크기 제한 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://codeconnect.cb4c0ey4oou3.ap-northeast-2.rds.amazonaws.com:3306/codeconnect
    username: codeconnect
    password: 12345678
    
# mybatis (dto를 주로 의미함 / 등록)
mybatis:
  type-aliases-package: com.code.*
  mapper-locations:
  - /mapper/**/*.xml



